[project]
name = "llmgrader"
version = "0.1"
dependencies = [
    "click>=8.0.0",
    "requests>=2.31.0",
    "pytest>=7.0.0",
    "coverage>=7.3.0"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"